# Generated by Django 4.0.6 on 2022-08-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('With own body weight', 'With own body weight'), ('With a weight', 'With a weight'), ('With time', 'With time')], default='With a weight', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
