# Generated by Django 4.0.6 on 2022-10-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_workout_avg_time_remove_workout_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
