# Generated by Django 4.0.6 on 2023-05-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_alter_workout_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Hidden', 'Hidden')], db_index=True, default='Public', max_length=20),
        ),
    ]
