# Generated by Django 4.0.6 on 2022-09-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticexercise',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
