# Generated by Django 4.0.6 on 2022-11-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_rating_unique_together'),
        ('stats', '0003_alter_statisticcalories_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise'),
        ),
    ]
